### ISSUE TITLE
iOS: getCurrentPosition timeout does not work and it blocks application execution

### ISSUE THREAD

**Issue by ppcano** [shazron/phonegap-questions#10]
I have experienced this problem with cordova 2.5 & 2.6 in iOS 6.1.3, iPhone 4.

Timeout param is not working, so I decided to implement the same behavior with timing-function, however _getCurrentPosition_  seems to be executed synchronously instead of asynchronously, and because _timeout_ does not work, neither locationTimeout function or error callback are executed and the application is blocked waiting for getCurrentPosition response.

``` js
      var positionError = function() {
           /// do something on error
      };
      var locationTimeout = window.setTimeout(function() {
          // work-around to solve timeout error
          positionError();
      }, 1000);

      navigator.geolocation.getCurrentPosition( function(response) {
          clearTimeout(locationTimeout);
          positionNext(response);
      }, function(error) {
          clearTimeout(locationTimeout);
          positionError();
      }, { maximumAge: 3000, timeout: 1000 });
```

Could I misunderstand any internal functionality?

**Comment by shazron** [comment]
Hmm this is strange, all of the Cordova APIs are async and should never block. Can you do an alert(navigator.geolocation.getCurrentPosition) just to check, and report the results whether it says "[native code]".

**Comment by ppcano** [comment]
The output is the cordova JS function:

title: index.html

``` js
function(successCallback, errorCallback, options) {
    argscheck.checkArgs('fFO', 'geolocation.getCurrentPosition', ...
    ......
```

**Comment by shazron** [comment]
Alright seems a legitimate issue we need to look into.

Please file an issue at:
http://issues.cordova.io

... so it can be tracked and evaluated by the devs, and you can be notified.

Sign up here:
https://issues.apache.org/jira/secure/Signup!default.jspa

Thanks!

**Comment by shazron** [comment]
Filed as: https://issues.apache.org/jira/browse/CB-3027
