### ISSUE TITLE
Iadplugin

### ISSUE THREAD

**Issue by Franciscoflores** [shazron/phonegap-questions#11]
Hi, thank you for your outstanding work. It is very usefull.
i cant install the iadplugin in phonegap with the latest Cordova.
Could it be possible to post a demo?
many thanks

**Comment by shazron** [comment]
Haven't touched the plugin lately, nor will I have the time. Plugin issues should be filed in their respective issue trackers. If you have a PhoneGap API question instead, I would be glad to help...
