### ISSUE TITLE
[iOS] Upgrading a plugin with an older method signature for Cordova/PhoneGap 2.7.0

### ISSUE THREAD

**Issue by shazron** [shazron/phonegap-questions#13]
When you use a method signature in JavaScript like this:

```
cordova.exec('MyService.myMethod', myArg1, myArg2, myArg3);
```

The console log will ask you to upgrade it like this:

```
The old format of this exec call has been removed (deprecated since 2.1). Change to: cordova.exec(null, null, "MyService", "myMethod", [ myArg1, myArg2, myArg3 ]);
```

But, if your corresponding Objective-C method uses the old signature like so:

```
- (void) myMethod:(NSMutableArray*)arguments withDict:(NSMutableDictionary*)options;
```

Update it to this new signature:

```
- (void) myMethod:(CDVInvokedUrlCommand*)command;
```

Also update any references to "arguments" in the method body with "command.arguments".

So if your method looked like this:

```
- (void) myMethod:(NSMutableArray*)arguments withDict:(NSMutableDictionary*)options
{
    NSString* myArgs1 = [arguments objectAtIndex:0];
    NSString* myArgs2 = [arguments objectAtIndex:1];
    NSString* myArgs3 = [arguments objectAtIndex:2];
}
```

Change it to this:

```
- (void) myMethod:(CDVInvokedUrlCommand*)command
{
    NSString* myArgs1 = [command.arguments objectAtIndex:0];
    NSString* myArgs2 = [command.arguments objectAtIndex:1];
    NSString* myArgs3 = [command.arguments objectAtIndex:2];
}
```

This is the easiest upgrade path. If you want to further use the more powerful callback mechanisms provided, see the [Plugin Development Guide](http://docs.phonegap.com/en/2.7.0/guide_plugin-development_ios_index.md.html#Developing%20a%20Plugin%20on%20iOS) to upgrade your plugin.

**Comment by padzilla** [comment]
Great info! I was kind of dreading doing this but it seems pretty straightforward. One quick question though.
If I wanted to get a specfic key, would it just be like this for example :

NSInteger myinteger = [[command.arguments objectAtIndex:0] objectForKey:@"mykey"] intValue];

Thanks again.

**Comment by shazron** [comment]
If the 1st item in the array is a dictionary (JSON object), yup

**Comment by dfsilva** [comment]
Thanks!
