### ISSUE TITLE
Using RequireJS with Cordova/Phonegap

### ISSUE THREAD

**Issue by TravelingTechGuy** [shazron/phonegap-questions#15]
Any chance you can post a gist with the correct/recommended RequireJS configuration (shim/path/etc.) that'd allow using RequireJS with Cordova/Phonegap?
I've seen several StackOverflow questions, with all kinds of workarounds, but I'd appreciate an "official" approach - and maybe something I can build a template around.

Thanks!

**Comment by shazron** [comment]
Sure thing. Note that the 'cordova' object is still bound globally.

See:
1. [index.html](https://gist.github.com/shazron/5639804)
2. [app.js](https://gist.github.com/shazron/5639820)

**Comment by TravelingTechGuy** [comment]
Thanks Shazron!
So, there's no need for any paths inclusion, or any shimmying?

**Comment by shazron** [comment]
No, what you see in my example is all you need

**Comment by SgtPooki** [comment]
What version of cordova is this using?

**Comment by SgtPooki** [comment]
Also, when using this method, plugins are not loaded. (for example, navigator.contacts)

I've been researching for about 12 hours to get phonegap working with requirejs, trying to override things and work around the conflicts.. there has got to be a solution to this somewhere. (i.e. your solution does not work)

**Comment by shazron** [comment]
My last comment was 3 months ago, so this was pre-3.0.0.
The default 3.0.0 PhoneGap new project installation does not have any core plugins - so no contact support is installed by default. How are you getting this setup?

**Comment by jdanlewis** [comment]
An example of setting up Phonegap 3.0 with RequireJS would be helpful!

**Comment by andy-polhill** [comment]
Agreed, I'm having a nightmare, ideally an example with Phonegap Build too, I'm on the the brink of refactoring out requireJS.

**Comment by jdanlewis** [comment]
@thatguynamedandy - I got Phonegap 3.0 working with RequireJS, Bootstrap, and JQuery. Check out this boilerplate:

https://github.com/jdanlewis/hello-phonegap-requirejs

**Comment by shazron** [comment]
Thanks @jdanlewis 
For the others, see his code: https://github.com/jdanlewis/hello-phonegap-requirejs/blob/45486294f220b7b67060b87473b2330c8f8c8063/www/js/app.js#L15-L27

**Comment by andy-polhill** [comment]
@jdanlewis thanks for that code, fixed my issue. In the end I put it in the callback method of my require config. Not sure how performant this is but it seems to work.

```
callback: function() {
    (function checkCordova() {
        //Check if Cordova exists
        if (window.cordova) {
            // Listen for the deviceready event
            document.addEventListener('deviceready', function() {
                require(['main']);
            }, false);
        } else {
            // If Cordova does not exist, check again in 1/60th second
            setTimeout(checkCordova, 16);
        }
    }());
}
```

**Comment by Bebhead** [comment]
@jdanlewis - Apologies if this is a silly question, but I'm relatively new to both phonegap and require.  But from what I understood when using requirejs you needed to have a script tag like this:

<script data-main="main" src="libs/require.js" type="text/javascript"></script>

in your index.html to point to your config file and the require.js file, and then load everything else as requirejs modules...  I noticed you do have a main.js, but don't see it referenced in the index anywhere...  Or does loading up that main.min.js file somehow take care of all of that?

**Comment by jdanlewis** [comment]
@Bebhead main.min.js is the output of the r.js optimizer and does include require.js, as configured by build.js. To use unoptimized code, you could use the following script tag:

```
<script data-main="js/main" src="js/lib/require.js"></script>
```

For more info, see: http://requirejs.org/docs/optimization.html

**Comment by Bebhead** [comment]
@shazron Is there any chance you can post a simple gist similar to the one you did for the initial post but for phonegap 3.0?  Dan's example seems nice, but the optimization and other libraries in there obfuscate things quite a bit for a beginner like me...

**Comment by gimelfarb** [comment]
If it helps anyone, I just spent hours trying to get it to work with PhoneGap 3.1.0, to realize what the problem was for me. It just wouldn't load require.js scripts on Android, but would work in Ripple emulator.

Basically in my `require.config` I had `baseUrl: '/js'`, to load by default from 'js' folder. The problem is that the `www` folder **is not the root folder** when running as a mobile app. That's why it was failing to resolve paths like `/js/app/init.js`. Of course, no error indication because debugging on the actual phone is **really hard**.

The fix is to have it as `baseUrl: 'js'` (without leading slash).
