### ISSUE TITLE
build to phone failing with iOS7 beta and Xcode 5 DP1

### ISSUE THREAD

**Issue by leemarrett** [shazron/phonegap-questions#16]
Been happily building to my phone with Xcode 4.6 (phonegap/cordova 2.5.0)

installed ios7 developer preview and Xcode 5 DP and now building to the phone fails.

(error screenshot here: http://d.pr/i/akfq, let me know if I can get specifics for you)

Build succeeds and runs fine in iOS simulator.

**Comment by shazron** [comment]
Hi - I'll let you know once I know what's going on - like you I've only tested this on the Simulator on Mavericks. In any case this will be solved before the next seed

**Comment by shazron** [comment]
Thanks leemarrett - but further discussion should occur here: https://issues.apache.org/jira/browse/CB-3768 so it can be tracked and fixed by any dev
