### ISSUE TITLE
Clipboard access

### ISSUE THREAD

**Issue by TravelingTechGuy** [shazron/phonegap-questions#17]
How can I copy text out of a textbox/textarea to the device's clipboard (vice versa is a given, I guess)?

**Comment by shazron** [comment]
iOS? The default textboxes should have this functionality built in (tap and hold to see options)

**Comment by TravelingTechGuy** [comment]
Both iOS and Android (WP8 - maybe later) - but I'd like to access it from JavaScript, ie, not have the user take an extra 2-3 taps (slect the input, long-click, select "Select all" and then select copy). Ideally, I'd like to either tell the user "content has been copied to clipboard" or have a single "copy this" button.

**Comment by shazron** [comment]
Not sure about the other platforms, but you could grab the value using js, and use a plugin to paste it into the Pasteboard in iOS: https://github.com/phonegap/phonegap-plugins/tree/master/iPhone/ClipboardPlugin

Note that the plugin is an older plugin, it may have to be upgraded.

**Comment by TravelingTechGuy** [comment]
Thanks for the reply. I was aware of the plugin - I was hoping there's either a more "native" way, or a better plugin.
Should I add clipboard access as a feature request to the Cordova repo?
Thanks!

**Comment by shazron** [comment]
You could: http://issues.cordova.io Thanks!
