### ISSUE TITLE
Close inAppBrowser with Done button on Youtube player

### ISSUE THREAD

**Issue by icyKira** [shazron/phonegap-questions#18]
I'm currently working on opening youtube videos using inAppBrowser on iOS.

Thing is when iOS opens this link, when you press play it opens youtube application or full screen mode that contains another Done button that is only used for closing that full screen mode.
You need to press Done button from inAppBrowser status bar in order to close inAppBrowser.

Is there anything I can do to trigger inAppBrowser close event when user taps on first Done button ?

I have used exectueScript but for plain html sites where I can get DOM element and bind event on it, can I do something similar here?

Thanks

**Comment by shazron** [comment]
The trick here is detecting that Done button from the YouTube video closing - are you able to do that? Not sure what happens in that case -- if somehow you can detect that (let me know), then yes you can close the InAppBrowser automatically after

**Comment by icyKira** [comment]
The problem is I don't know if I can detect this Done button from the Youtube video closing. I used this approach on other regular sites to track what is user doing but there I can use selectors and other stuff, here I don't know. I'll post here if I find solution to this problem.

Thanks.
