### ISSUE TITLE
InAppBrowser - resize?

### ISSUE THREAD

**Issue by sendtoab** [shazron/phonegap-questions#19]
Hi,

Is there any way I can set the height of an IAB window? I call an IAB instance, then load a table on the page, but I can't scroll down the table as the inappbrowser seems to constrain the window.

Is there a way I can set the height of the IAB window to accommodate my content?

Thanks

**Comment by shazron** [comment]
Not sure exactly what you mean, why is it not scrollable? What platform are you testing on.

Some sample code for me to verify on my end would be great as well.
