### ISSUE TITLE
PrintPlugin Not Working After Loading XSL

### ISSUE THREAD

**Issue by surajshaha** [shazron/phonegap-questions#2]
Hello,

I have developed an iOS App using Corodova Phonegap 1.9.0,and was able to successfully compiled and build the PrintPlugin,but this plugins works only on first page of the app i.e index.html but when i Logged in and Read XML(using XSL generated output for next page) then on the next page this plugin is not working  I can't trace out what is this issue ??? Coz I can see the code for Print function when I put  an alert(window.plugins.printPlugin.print);
 but then nothing happens ????
This is strange as this plugin works on the first page but it is not working on the second page.
I have used iframe on the second page,is this issue related to iframe????
Am I missing anything???

Please Help.

**Comment by shazron** [comment]
Provide some self-contained sample code that I can see.

**Comment by surajshaha** [comment]
Please find images for code snppets:
![Html-Head](https://f.cloud.github.com/assets/3158888/301806/85c771aa-95ea-11e2-8e5e-9a0ffd5a7e93.png)
![Html-Body](https://f.cloud.github.com/assets/3158888/301807/8f0ade3c-95ea-11e2-8e75-cafba5dfd277.png)

Coz pasting code in this portal is disturbing the text alignment.

**Comment by shazron** [comment]
Hmm, I believe its related to the iframe - is the xsl result also loading cordova.js? if not, of course it can't call any PhoneGap API functions.

**Comment by surajshaha** [comment]
Hi Shazron,

I was able to get print plugin working but It prints only first page,I have a canvas which contains the report to be printed who's height is almost 200%( twice),Is there any work around or method to get fit to screen printing of the canvas image? Or get the half part printed on second page?
Thanks in Advance!!!!!

**Comment by shazron** [comment]
This delves into details of a particular plugin and not PhoneGap, don't think I can help you more here. I think the problem lies in this second comment, with a fix: http://forums.macrumors.com/showthread.php?t=1437451
