### ISSUE TITLE
Write to Phonestorage iOS ( write string data to a file and save file as xml) 

### ISSUE THREAD

**Issue by surajshaha** [shazron/phonegap-questions#20]
Hi  @shazron,

I want to save the data (a string) retrieved from the server(using ajax) to Phone Storage(not web storage) as a xml file.

Is it possible using File APIs ? If yes then how ? coz I tried by writing a sample app and tried to write to simple txt but the file is not updated (code compiles and runs without error). 
Thanks for the Help.

Regards,
Suraj

**Comment by shazron** [comment]
It definitely works. Try out the samples in the docs: http://cordova.apache.org/docs/en/3.0.0/cordova_file_file.md.html#FileWriter

It can only write text, so convert your xml to text first.
