### ISSUE TITLE
Why is this forum not made more prominent?

### ISSUE THREAD

**Issue by dschien** [shazron/phonegap-questions#22]
I spent about 8 hours trying to get cordova work with require to get the Barcode scanner plugin work. Both, require and phonegap are new to me, so I appreciate that I need longer but this was such an unpleasant experience. 

All other libraries work alright with require with the recipes that are out there. I wouldn't  care that the cordova library needs to do things differently (with the result that these normal procedures break) if this was clearly documented in a central place and pointed to by the official documentation. Sadly, this isn't the case. The documentation is patchy and the bits of information that are around rarely state the version number of cordova or involved libraries.

**Comment by shazron** [comment]
This is not an official support forum - I use this mainly for people that email me questions, and the main purpose is stated in the README.md. Which repo did you get the Barcode scanner plugin from? The one from the PhoneGap Build repo would work best I imagine. 

If any docs are to be updated (and we hear your concerns) it would be at:
http://docs.cordova.io for the Cordova CLI tool
and
http://docs.phonegap.com for the PhoneGap CLI tool 
(http://docs.phonegap.com/en/3.0.0/guide_cli_index.md.html)
