### ISSUE TITLE
Using RequireJS with Cordova/Phonegap that is compatible with browsers

### ISSUE THREAD

**Issue by dschien** [shazron/phonegap-questions#23]
Related to issue 15:
Thanks for your help there. 

Sadly, as it stands, this approach works with cordova 3.0.1 and require 2.1.8
it won't run in a browser.

Do you have any suggestions how I should mock out a cordova.js to make your suggested solution work? 

``` JavaScript
requirejs(['cordova.js', 'js/app.js'], function (garbage, app) {
    var exec = cordova.require('cordova/exec');
```

Or maybe mocking isn't the preferred option? I just want to develop locally and don't want to make hard coded changes for device deployment.

Many thanks

**Comment by shazron** [comment]
Our focus hasn't been with browser support, so we haven't tested there, although you may have success with the Ripple Emulator http://emulate.phonegap.com

What exactly is not working?
