### ISSUE TITLE
Is there any possibility to integrate an asp.net application in a PhoneGap application?

### ISSUE THREAD

**Issue by simi0893** [shazron/phonegap-questions#25]
Hello, 
I've got a big problem to solve. The thing is, that I already have an asp.net application written in C# for mobile devices. But now it would be nice if it'd be possible to access some native device features. Since I don't want to write a native code for every platform, I tried to do this with phonegap. But the problem is that I still want to use the code of my asp.net application. Is there any possibility to combine PhoneGap with an asp.net application that is stored on a remote server? 

I know that PhoneGap is not designed to do this (I've already read the PhoneGap API Docs and several articles) but maybe you've still got an idea how to solve this problem! 

Thanks in advance for your answers.

**Comment by shazron** [comment]
Unfortunately, as you have discovered, this is not possible with PhoneGap. Xamarin (http://xamarin.com/ios) is your best bet.

**Comment by simi0893** [comment]
I built a phonegap app and added the following code line to index.html:
document.location.href = "myapplication.aspx";
It worked. What do you think about this solution?

Xamarin is not an alternative, as you can only build for iOS and Android and you have to pay for it. But thanks for your tip!

**Comment by shazron** [comment]
It will never pass the App Store review process, sorry.
