### ISSUE TITLE
Photo library preview! (IOS)

### ISSUE THREAD

**Issue by fernandopg** [shazron/phonegap-questions#27]
I use navigator.camera to choose an image from PHOTOLIBRARY, when the user click in the miniature image, it is selected and return to my app.

Are there any option to show a preview of the image in fullscreen before choose the image? If I use the allowEdit option to true, there are a preview but also crops the image... and I need the full image...

I can make a preview in js with two buttons (CANCEL and CHOOSE) but if the user cancel y want return to the same position and album the user was.... 

Hope you understand me... sorry for my English... ;-)

**Comment by shazron** [comment]
As far as I know, no. The preview is only available for the Camera option, not PHOTOLIBRARY.
