### ISSUE TITLE
Loading cordova.js, etc. from remote host

### ISSUE THREAD

**Issue by mckamey** [shazron/phonegap-questions#28]
1. Are there any known issues with cordova.js and its supporting files are loaded from a remote server, rather than locally? I understand the trade-offs between local / remote, latency, etc. I'm asking from a Cordova perspective if it is all expected to run as usual. Will it still be able to communicate as expected to the native components?
2. A follow up to the question is: does cordova.js bootstrapping up through deviceready before loading the remote instances of these scripts? I.e, is there any initialization that requires it to be local before being remote, or can it directly redirect the location.href to a remote app?

**Comment by shazron** [comment]
1. It should run fine. All issues we know about relating to this are in the issue tracker: https://issues.apache.org/jira/issues/?jql=project%20%3D%20CB%20AND%20text%20~%20remote%20ORDER%20BY%20updated%20DESC
2. No initialization is needed that requires it to be local before being remote.

**Comment by mckamey** [comment]
I can confirm that loading remotely does appear to allow access to native components (when scripts are properly loaded, see #29) and that `cordova.js` does not appear to need to be loaded by the local `index.html` bootstrap.

**Comment by JanMisker** [comment]
I am looking for similar information, so thought to add my question here.
Remote loading of index.html and thus related JS seems to work, however I wonder if it is also possible to have a local fallback of index.html and all JS. So the app would load from local, and the local resources would be replaced  when the server version is updated. 
I remember I saw an article by someone who did something like this, but I can not find it again.

Perhaps a cache manifest could work but I would like something that can be controlled a bit better.

**Comment by shazron** [comment]
What you could do is:
1. Download your updated resources to persistent storage (using the File Transfer and File API) under a subfolder
2. When your local index.html loads, check for existence of the updated resources
3. Redirect (through window.location) to the updated resource

Is this what you are looking for?

**Comment by JanMisker** [comment]
Yes that's the idea. Will calls to plugins still work in this setup? Anyway I will try it out.

**Comment by davidpfahler** [comment]
@shazron What do you mean by a subfolder? Would you use `cordova.file.dataDirectory` to save these file to or something else? Can I load javascript using `<script src="file://...>` to load javascript files in this directory? Thanks for any help you can give.

**Comment by davidpfahler** [comment]
For others coming here to find answers: You can load javascript and css files from the `cordova.file.dataDirectory` by simply using a file url. You should construct this file url by using `cordova.file.dataDirectory` plus whatever you file path is, e.g. `scripts/main.js`.

**Comment by shazron** [comment]
@davidpfahler correct
