### ISSUE TITLE
Compacting/combining cordova.js and plugins?

### ISSUE THREAD

**Issue by mckamey** [shazron/phonegap-questions#29]
As a distinct follow up question to Issue #28, is there any recommended way to pre-package the cordova.js and all the plugin scripts? I have mechanisms of my own, but it looks like a lot of the logic expects these files to sit individually and be loaded as required. If I manually prepackage, I'm concerned it might break the requireJS loading logic.

I like the modularity of this approach, but once a feature set has been settled upon it becomes much chattier than if everything is built as a smaller number of compacted scripts. Again this isn't as big of a deal locally but thinking of the remote scenario, it goes against [commonly accepted best practices](http://developer.yahoo.com/performance/rules.html).

**Comment by shazron** [comment]
cordova.js needs to be loaded first before any plugin scripts, so add it to the top of the combined script first.

The plugin js themselves, if you look at Media plugin for example:
https://github.com/apache/cordova-plugin-media/blob/master/www/Media.js

...they are missing the cordova.define wrapper, which is added by plugman/cordova CLI when the plugin is installed.

More info in the Plugin Spec <js-module> tag, specifically the part that mentions cordova.define:
http://cordova.apache.org/docs/en/3.0.0/plugin_ref_spec.md.html

You can see how the plugin adds the wrapper after you add it, it should be in your "www/plugins" folder (if using the CLI, it should be in your platforms/[platform_name] folder)

**Comment by mckamey** [comment]
Thanks, @shazron. So just to reiterate to make sure I understand: compaction is okay but I should use the versions emitted by `plugman` CLI into the project, which will add those `cordova.define` wrappers. Should I still include the `cordova_plugins.js` or is that just for locating the other scripts?

For example, if I want to compact cordova and the contacts plugin, I added all of these scripts listed in `cordova_plugins.js`. So the contacts plugin should work if I include all these in this order?

```
/cordova.js
/cordova_plugins.js
/plugins/org.apache.cordova.contacts/www/contacts.js
/plugins/org.apache.cordova.contacts/www/Contact.js
/plugins/org.apache.cordova.contacts/www/ContactAddress.js
/plugins/org.apache.cordova.contacts/www/ContactError.js
/plugins/org.apache.cordova.contacts/www/ContactField.js
/plugins/org.apache.cordova.contacts/www/ContactFindOptions.js
/plugins/org.apache.cordova.contacts/www/ContactName.js
/plugins/org.apache.cordova.contacts/www/ContactOrganization.js
/plugins/org.apache.cordova.contacts/www/ios/contacts.js
/plugins/org.apache.cordova.contacts/www/ios/Contact.js
```

**Comment by shazron** [comment]
Hmm now I'm not so sure. cordova_plugins.js is actually dynamically loaded by cordova.js, and cordova_plugins.js actually defines the locations of the other plugin js, and dynamically loads that as well. So compaction does not really help in this case.

I'll ask around -- but what your case needs is a way to instantiate the plugin code in memory without loading from file.

**Comment by mckamey** [comment]
Following up with my findings: compacting `cordova.js` with the rest of the app's scripts seems to work fine, but `cordova_plugins.js` and the `plugins` directory must sit at the root and not be combined. This is unfortunate but at least a partial work around. It would be nice to combine these at build time since they won't change for a given deployment. This also would allow setting far future cache headers by having the compacted scripts change name with each version.

**Comment by andrewreedy** [comment]
https://github.com/andrewreedy/cordova-loader

**Comment by shazron** [comment]
@mckamey @andrewreedy Right now there is experimental (beta, in progress) support for this built-in. See http://markmail.org/message/rrv7rnlvv6zor2r6

**Comment by andrewreedy** [comment]
@shazron that doesn't combine the core cordova.js and plugins. It just copies them to the www folder. right?

**Comment by shazron** [comment]
no, it combines everything - cordova js and plugin js into one js file, à la browserify (bundling up all dependencies): http://browserify.org/

**Comment by andrewreedy** [comment]
oh weird, I asked Suraj and he said that https://github.com/apache/cordova-cli/pull/185#issuecomment-51656189

**Comment by shazron** [comment]
Hmm that is definitely not the intent I don't think. In any case, what I said would be the eventual goal -- that is what browserify is all about after all!

**Comment by shazron** [comment]
I went back to the comment by @imhotep - the browserify option's original author: http://markmail.org/message/nw43h36qoaiug4kl
"....will generate a browserify version of cordova.js. Plugins and everything is bundled in." 

Perhaps @surajpindoria can clarify what he meant.

**Comment by andrewreedy** [comment]
Okay awesome! that will be awesome once they get it built in!

**Comment by surajpindoria** [comment]
Sorry, I was getting confused by two different things.  My mistake @andrewreedy
