### ISSUE TITLE
Error building cordova-osx projects

### ISSUE THREAD

**Issue by neiltron** [shazron/phonegap-questions#3]
I'm not sure if I'm even doing this right, but when I try to build a cordova-osx project in XCode I get the following error:

```
dyld: Symbol not found: _OBJC_CLASS_$_NSObject
  Referenced from: /Users/neil/Library/Developer/Xcode/DerivedData/QuittingTime-cuqdmvrakpuntfcoeuvzkoglcouw/Build/Products/Debug/Cordova.framework/Versions/A/Cordova
  Expected in: /usr/lib/libobjc.A.dylib
 in /Users/neil/Library/Developer/Xcode/DerivedData/QuittingTime-cuqdmvrakpuntfcoeuvzkoglcouw/Build/Products/Debug/Cordova.framework/Versions/A/Cordova
(lldb) 
```

The cordova-osx docs are (understandably) thin, so I'm not sure if I'm even supposed to be building in XCode or if there's another method. I've tried linking the Foundation and CoreFoundation frameworks with no luck.

**Comment by shazron** [comment]
Hi @neiltron how are you building and creating the project? Through bin/create right?

**Comment by neiltron** [comment]
Yeah. cordova-osx is in `/usr/local/lib/node_modules/cordova/lib/cordova-osx`

From that directory, I'm calling `bin/create ~/projects/myapp com.blurgh.myapp MyApp`. Then I open MyApp.xcodeproj, hit run, and get that error.

I'm running OS X 10.7.5 with Xcode 4.6.1.

**Comment by shazron** [comment]
Wait a minute, it's working in the node module? News to me :) I don't think os x is supported for the node module yet: https://npmjs.org/package/cordova

I know it works if you grab it from https://github.com/apache/cordova-osx

**Comment by neiltron** [comment]
I think I may have just cloned it into the node_module dir along with the ios/android libs. I tried cloning cordova-osx to a clean dir and creating a fresh project and I'm getting the same error message.

Most of my googling points to it maybe being some change in the location of NSObject between 10.7 and 10.8. I have mountain lion on a laptop at home, so I can give that a shot later this afternoon.

**Comment by shazron** [comment]
That must be it (Lion vs Mountain Lion) - I'll see if I can test under Lion in a VM.

**Comment by shazron** [comment]
Confirmed. On Lion, the "Latest OS X" shows as 10.8(!!). Clearly an Xcode bug here:

![Screen Shot 2013-03-25 at 2 11 43 PM](https://f.cloud.github.com/assets/36107/300221/0fb061ce-9591-11e2-970d-2dc00f02b0f3.png)

**Comment by neiltron** [comment]
I tried changing that to "Current OS X" (and 10.6/10.5 because why not) and it didn't seem to change things for me. BTW, thanks for taking the time to look into this.

**Comment by shazron** [comment]
Current? I don't see the option. I changed it manually to 10.7 and it compiles (well 1 error, but un-related, more an ARC thing that I'm trying to fix). I filed an issue: https://issues.apache.org/jira/browse/CB-2804

**Comment by shazron** [comment]
D'oh I didn't see Current OS X. So I set it in the Project and Target, and it compiles (besides that 1 error, which I filed: https://issues.apache.org/jira/browse/CB-2805)

**Comment by shazron** [comment]
ALso: change the deploy target and base sdk of the Cordova.framework project itself

**Comment by shazron** [comment]
More ARC issues. I've fixed all of them, and checking in the fixes. Works on 10.8 and 10.7 now :)

**Comment by shazron** [comment]
They are committed in the Apache repos - should be mirrored in Github soon.

**Comment by neiltron** [comment]
Wow, thanks man. I will try your changes out on my office machine tomorrow morning. It works on my laptop as is.

**Comment by neiltron** [comment]
Works great for me now. Thanks again Shazron.
