### ISSUE TITLE
Is there a way to read all images from the photo library?

### ISSUE THREAD

**Issue by ghost** [shazron/phonegap-questions#31]
I am building an ios photo gallery app which initially should scan photo library folder and then display all images in my application automatically, without asking the user to select individual photos. I am aware of camera.getPicture api, however since I need to do it for all images this will not work. Is there a way I can scan the entire photo library on ios devices and display them to the user in my phonegap application using phonegap api?

**Comment by shazron** [comment]
I'm afraid not, using any of the core plugins. I don't think there is a non-interactive way to get access to photo library data using the iOS SDK - but please double check on this

**Comment by ghost** [comment]
thank you for getting back to me. I will definitely keep digging, and if i find an answer i will paste it here for others.

**Comment by darkyen** [comment]
Ping ?
