### ISSUE TITLE
html as asset & cordova plugin add error details

### ISSUE THREAD

**Issue by Red-Folder** [shazron/phonegap-questions#32]
Started to convert my plugin over to the Plugman spec, but I seem to be struggling with a couple of things and hoping for some pointers:

1) I've an asset line which copies a html file in to www (see https://github.com/Red-Folder/bgs-sample/plugin.xml) - but it just doesn't seem to copy the file into the project.  Can html files be used with the asset tag?
2) Is there a good way to see more verbose information when doing a "cordova plugin add"?  I use the -d, but I've had a fair number of errors with little explanation why.  Generally its because I've done something stupid in the plugin.xml, but trying to find and fix is very trial and error.  I assume there is a better way.

**Comment by shazron** [comment]
1. It should work with any file. I don't have access to that file you linked - perhaps paste it as a public gist.
2. cordova plugin add does not validate the plugin.xml though - that's something we want to work on. It is a work in progress: https://issues.apache.org/jira/browse/CB-4195

**Comment by Red-Folder** [comment]
Sorry,  didn't check the url I posted.  Should have been:

https://github.com/Red-Folder/bgs-sample/blob/master/plugin.xml

I've tried the asset inside and outside of the platform block. I'll look at it again when next week - I'm bound to have done something stupid.

**Comment by shazron** [comment]
Ok, did some testing. The **myService.html** is actually copied into your platform specific www after the first **"cordova prepare"** (which is implicitly called when you do **"cordova build"** for example). 

In your project, navigate to:

```
platforms/android/assets/www
```

... and you should find your asset.

**Comment by Red-Folder** [comment]
Shazron

Deleted everything and started again from scratch - all works perfectly.

Don't you just love it when you don't understand why it worked as much as when it doesn't.

Apologies for wasting your time.  Thanks for the quick response.
