### ISSUE TITLE
Phonegap build on Mac

### ISSUE THREAD

**Issue by chopperbilly** [shazron/phonegap-questions#33]
What happens is that my project name is MadcapMobile (a dairy industry  app, for ios) but when I do a build from the command line, I get errors for each phonegap included plugin (which I have added correctly, e.g. for Camera, File, FileTransfer), but not on a plugin from bitbucket. An example follows

sh-3.2# phonegap build ios
[phonegap] detecting iOS SDK environment...
[phonegap] using the local environment
[phonegap] compiling iOS...
   [error] An error occurred while building the ios project.*\* BUILD FAILED **

The following build commands failed:
                Check dependencies
(1 failure)
2013-12-18 15:27:59.574 xcodebuild[16270:5103]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-3575/Xcode3Sources/XcodeIDE/Frameworks/DevToolsBase/pbxcore/SpecificationTypes/XCGccMakefileDependencies.m:78
Details:  Failed to load dependencies output contents from ``/usr/local/bin/MadcapMobile/platforms/ios/build/MadcapMobile.build/Debug-iphonesimulator/MadcapMobile.build/Objects-normal/i386/CDVFileTransfer.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “CDVFileTransfer.d” couldn’t be opened because there is no such file." UserInfo=0x7fb0265310a0 {NSFilePath=/usr/local/bin/MadcapMobile/platforms/ios/build/MadcapMobile.build/Debug-iphonesimulator/MadcapMobile.build/Objects-normal/i386/CDVFileTransfer.d, NSUnderlyingError=0x7fb0265526a0 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/usr/local/bin/MadcapMobile/platforms/ios/build/MadcapMobile.build/Debug-iphonesimulator/MadcapMobile.build/Objects-normal/i386/CDVFileTransfer.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.

(and two more, for File and Camera)

Then:
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
*\* BUILD FAILED **

ALSO:

The following build commands failed:
                CompileC build/MadcapMobile.build/Debug-iphonesimulator/MadcapMobile.build/Objects-normal/i386/CDVFile.o HelloWorld/Plugins/org.apache.cordova.file/CDVFile.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
                CompileC build/MadcapMobile.build/Debug-iphonesimulator/MadcapMobile.build/Objects-normal/i386/CDVFileTransfer.o HelloWorld/Plugins/org.apache.cordova.file-transfer/CDVFileTransfer.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
                CompileC build/MadcapMobile.build/Debug-iphonesimulator/MadcapMobile.build/Objects-normal/i386/CDVCamera.o HelloWorld/Plugins/org.apache.cordova.camera/CDVCamera.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(3 failures)

BUT - NOTE: There is no HelloWorld project on the Mac machine.!!!!

, where it tries to use ……HelloWorld instead of …MadcapMobile, but ONLY for the plugins. I’m using phonegap version 3.3.0, I have the latest Xcode, and a lot of what appears to be successful compiling happens before the errors.

**Comment by chopperbilly** [comment]
I have deleted and re-created the app, to no avail.

**Comment by chopperbilly** [comment]
Didn't mean to close it!

**Comment by shazron** [comment]
What is the _exact_ command you used to create the project? Plus anything you did after? Provide this log, I'll verify on my end if I can reproduce the results.

**Comment by chopperbilly** [comment]
Hi Shazron,

Only just got back to work after holiday.

My command to create was: _phonegap create MadcapMobile_

(Can’t remember if I told you, but MADCAP stands for Milk Analysis Data
Collection and Processing – we do a lot of work for the manufacturing Dairy
Industry, both here in NZ, Australia, and more recently in the US.)

What I can’t understand is that, search as I might, I can find no evidence
of “HelloWorld” anywhere on the Mac machine, so how/why it is trying to
locate a HelloWorld folder or anything else I just can’t fathom. (See
errors).

Many thanks for getting back to me – hope you had a good Christmas.

Regards, Bill.

_From:_ Shazron Abdullah [mailto:notifications@github.com]
_Sent:_ Monday, 23 December 2013 1:35 p.m.
_To:_ shazron/phonegap-questions
_Cc:_ chopperbilly
_Subject:_ Re: [phonegap-questions] Phonegap build on Mac (#33)

What is the _exact_ command you used to create the project? Plus anything
you did after? Provide this ;pg, I'll verify on my end if I can reproduce
the results.

—
Reply to this email directly or view it on
GitHubhttps://github.com/shazron/phonegap-questions/issues/33#issuecomment-31099942
.

**Comment by shazron** [comment]
Hi,
The "phonegap create" command has two more parameters (since its based on the cordova CLI), I'm filing an issue for this confusion with the devs.

Try:

```
phonegap create MadcapMobile my.project.id.here MadcapMobile
```

The second parameter is the bundle id of the project, and the third parameter is the project name. HelloWorld was just the default used if the parameters are not defined.

**Comment by shazron** [comment]
Actually the "phonegap create" help has the available options listed. On the command line run:

```
phonegap create
```

... to see the help text.

**Comment by chopperbilly** [comment]
Hi Shazron,

We’ve got it working. I did what you suggested after deleting everything to
do with the original, and all is working.

Thank you for your help.

Kind regards,

Bill.

_From:_ Shazron Abdullah [mailto:notifications@github.com]
_Sent:_ Tuesday, 7 January 2014 9:52 a.m.
_To:_ shazron/phonegap-questions
_Cc:_ chopperbilly
_Subject:_ Re: [phonegap-questions] Phonegap build on Mac (#33)

Actually the "phonegap create" help has the available options listed. On
the command line run:

phonegap create

... to see the help text.

—
Reply to this email directly or view it on
GitHubhttps://github.com/shazron/phonegap-questions/issues/33#issuecomment-31685770
.

**Comment by shazron** [comment]
No worries, glad to help!
