### ISSUE TITLE
draw on the screen (signature) and capture it ,save as a image or store locally 

### ISSUE THREAD

**Issue by surajshaha** [shazron/phonegap-questions#34]
Hi Shazron,

I have phonegap app for iOS,and would like to add draw signature feature in my app.Is there any plugin available to to the same ?

Regards,
Suraj

**Comment by shazron** [comment]
The site is down, but the first search term would show you how to (using HTML5 canvas):
https://www.google.com/search?q=exploring%20canvas%20drawing%20techniques

That is to capture a signature, then you would use Canvas2Image plugin:
https://github.com/devgeeks/Canvas2ImagePlugin
