### ISSUE TITLE
New inAppBrowser functionality

### ISSUE THREAD

**Issue by icyKira** [shazron/phonegap-questions#35]
Currently while using inAppBrowser  plugin we can't implement adding passes from the UIWebView.

Would it be possible for inAppBrowser to address these changes, in order for users of inAppBrowser plugin to be able to download passes on their iOS 6+ devices.

https://developer.apple.com/library/ios/technotes/tn2302/_index.html#//apple_ref/doc/uid/DTS40013009-CH1-DISTRIBUTING_PASSES-I_M_USING_A_UIWEBVIEW_IN_MY_APP_AND_IT_DOES_NOT_AUTOMATICALLY_SUPPORT_ADDING_PASSES_TO_PASSBOOK___WHAT_SHOULD_I_DO_

**Comment by shazron** [comment]
For this feature request, please file an issue at:
http://issues.cordova.io

... so it can be tracked and evaluated by the devs, and you can be notified.

Sign up here:
https://issues.apache.org/jira/secure/Signup!default.jspa
