### ISSUE TITLE
i am working on phonegap apps .apps need to login via twitter and facebook for ios and android. i did facebook login .but not able to do twitter.pls help me .what is best way to do this . 

### ISSUE THREAD

**Issue by somsin** [shazron/phonegap-questions#36]

**Comment by shazron** [comment]
You will have to find a Twitter Cordova/PhoneGap plugin. Did you actually check Google?:
https://www.google.com/search?q=Twitter+PhoneGap+plugin

This repo is for PhoneGap/Cordova questions, not for third-party integration questions. If I know more coincidentally, I would offer it, but in this case I don't, sorry.

**Comment by somsin** [comment]
yes i have checked this link but .it is using child browser. i want to use
Inappbrowser .for both ios and android.

thanks

On Fri, Mar 14, 2014 at 12:23 AM, Shazron Abdullah <notifications@github.com

> wrote:
> 
> You will have to find a Twitter Cordova/PhoneGap plugin. Did you actually
> check Google?:
> https://www.google.com/search?q=Twitter+PhoneGap+plugin
> 
> This repo is for PhoneGap/Cordova questions, not for third-party
> integration questions. If I know more coincidentally, I would offer it, but
> in this case I don't, sorry.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/shazron/phonegap-questions/issues/36#issuecomment-37572402
> .

## 

Thanks & Regards
Somendra Singh

**Comment by shazron** [comment]
InAppBrowser docs are here: https://github.com/apache/cordova-plugin-inappbrowser/blob/dev/doc/index.md

**Comment by somsin** [comment]
please can you tell me how to integrate in  InAppBrowser  .  i used http://oodlestechnologies.com/blogs/Twitter-integration-on-PhoneGap-using-ChildBrowser-and-OAuth-for-iOS-and-Android-Platforms 
this link to integrate twitter ,i used src="jquery-1.8.2.js"></script>
        <script type="text/javascript" charset="utf-8" src="jsOAuth-1.3.6.js
but dont want to use ChildBrowser.js in ios and android . i want to use InAppBrowser. so where to i change the code in index.html please help me.thanks

**Comment by somsin** [comment]
last 3,4 days i am not able to solve this problem

**Comment by shazron** [comment]
Again, this is not a how to integrate with Twitter with InAppBrowser issue tracker. If you have _specific_ issues with InAppBrowser, after trying something, with code, then maybe I can help you. What I would tell you is what I would have Googled anyway.
