### ISSUE TITLE
Remotely Loading an Cordova/PhoneGap App

### ISSUE THREAD

**Issue by ghost** [shazron/phonegap-questions#37]
In regards to Cordova 3.4:

I have come across various posts on the internets about doing a remote load of a webpage with cordova/phonegap and I have not been able to get it to work. I have read questions #28 and #29.

I am loading the url directly via the content setting in config.xml (the below example is on my local dev machine, but doesn't matter which url I use within our corporate firewall). I have also tried doing a window.location to the url, but that doesn't work either.

```
<content src="http://192.168.96.97:3004/#reference" />
```

The page loads fine except for the deviceready event doesn't fire. The www files local to the cordova app works, just nothing remote.

I get:

```
deviceready has not fired after 5 seconds.                cordova.js?body=1:1117
Channel not fired: onCordovaInfoReady                    cordova.js?body=1:1110
Channel not fired: onCordovaConnectionReady        cordova.js?body=1:1110
```

Here is my code:

```
<html>
<head>
<title>Cordova Test</title>
<script src="cordova.js"></script>
<script src="cordova_plugins.js"></script>
<script src="plugins/org.apache.cordova.device/www/device.js"></script>
<script src="plugins/org.apache.cordova.geolocation/www/Coordinates.js"></script>
<script src="plugins/org.apache.cordova.geolocation/www/PositionError.js"></script>
<script src="plugins/org.apache.cordova.geolocation/www/Position.js"></script>
<script src="plugins/org.apache.cordova.geolocation/www/geolocation.js"></script>
<script src="plugins/org.apache.cordova.network-information/www/network.js"></script>
<script src="plugins/org.apache.cordova.network-information/www/Connection.js></script>
<script>

// Wait for device API libraries to load
function onLoad() {
    alert("onload..."); // this displays
    document.addEventListener("deviceready", onDeviceReady, false);
}

// device APIs are available
function onDeviceReady() { // this never fires
    // Now safe to use device APIs
    alert("deviceready...");
    console.log("deviceready...");
}

</script>
</head>
<body onload="onLoad();" style="">
hello! :)
</body></html>
```

Thanks!

**Comment by shazron** [comment]
Hi, let's have a common project to work off. I'm using cordova-ios 3.4.1-x.x.x
1. Create a new project:

`cordova create Issue37 issue.37 Issue37`
1. Go into the project folder:

`cd Issue37`
1. Add the iOS platform:

`cordova platform add ios` 
1. Modify config.xml in the project root to edit <content src>

`<content src="http://localhost:8080" />`
1. Run this once:

`cordova prepare`
1. Run this:

`http-server platforms/ios/www`
(you might need to install the http-server module from npm)
1. Run the emulator:

`cordova emulate`

You should get the deviceready event showing. Note that you should only edit files in the www folder of the Project root. (Everytime you run cordova emulate, it will run cordova prepare so the root www changes get propagated to the platform www).

I installed the device plugin, and I was able to query the device data remotely. However, any xhr requests you have on your remote page are now restricted according to CORS.

As an example of a remote url working, see Adobe's PhoneGap developer app at http://app.phonegap.com

More info, and the app source is available also: http://phonegap.com/blog/2014/04/23/phonegap-developer-app/

**Comment by shazron** [comment]
Re-open if still an issue, and using my suggested method in the above comment.

**Comment by genru** [comment]
@shazron I tried to reproduce your instruction. but could not get your conclusion, i use phonegap 4.2.0-0.25.0.
app could not connect device successful. 

dose this instruction out of date?

UPDATE: my mistake, this still work.
