### ISSUE TITLE
Unable to Test Print Plugin on Cordova 2.7.0

### ISSUE THREAD

**Issue by surajshaha** [shazron/phonegap-questions#38]
Hi Shazron,

Recently I upgraded my app from Cordova 1.9.0 to 2.7.0,and also updated PrintPlugin's .h and .m files to use the new signature supported beginning in Cordova 2.1.0 is:
- (void)myMethod:(CDVInvokedUrlCommand*)command;

and replaced arguments by command.arguments ,and made other changes,added entry in config.xml. But no success.

And when I added alert to see if plugins are supported: alert(window.plugins) ==> undefined

Am I missing anything??? or Plugin calling signatures are different in cordova 2.7.0 ??

Also I noticed  "Resetting plugins due to page load" log in the console. ?????

The plugin is working great on Cordova 1.9.0.

Please help. I am stuck with this issue.

Regards,
Suraj

**Comment by shazron** [comment]
Upload the plugin files and js somewhere (Github?), I can take a look.

**Comment by surajshaha** [comment]
https://groups.google.com/forum/#!topic/phonegap/Vnaw7wvoZQE

**Comment by shazron** [comment]
Cordova.addConstructor is unsupported. Just don't use it, use the code inside it directly.
