### ISSUE TITLE
plugins in CordovaLib WebView

### ISSUE THREAD

**Issue by krisrak** [shazron/phonegap-questions#40]
I'm trying to implement CordovaLib WebView in iOS app with plugins. Not using CLI, i'm developing native app with one of the viewController that loads Cordova WebView.

I have implemented using the instructions and working, but the plugins does not seem to be enabled, can you tell what needs to be done to enable accelerometer for example?

Here is what I have done:
- added CordovaLib project to my main project
- added CDVAccelerometer.h and CDVAccelerometer.m, CDVDevice.h and CDVDevice.m to my main ios project
- created cordova_plugins.js with accelerometer.js and device.js...
- I'm starting [CDVViewController new] and all that stuff
- I can see that my webview.pluginsMap has accelerometer
- my config xml in the iOS project, looks like this, is this the right way to enable plugins in CordovaLib?

```
<widget id="com.webview.webview" version="0.0.1">
    <name>Cordova Container</name>
    <description>
        Cordova Container
    </description>
    <author email="krisrak@gmail.com" href="">
    </author>
    <access origin="*" />
    <feature name="Device">
        <param name="ios-package" value="CDVDevice" />
    </feature>
    <feature name="Accelerometer">
        <param name="ios-package" value="CDVAccelerometer" />
    </feature>
</widget>
```

anything else missing?

I get undefined when running navigator.accelerometer.watch... in Cordova WebView

**Comment by shazron** [comment]
Try using [plugman](https://www.npmjs.org/package/plugman) to install the plugins.

If you look into the plugin JavaScript, they are wrapped with cordova.define, and that is specific for use within the CLI/plugman. 

You don't need to add it to cordova_plugins.js nor create it - if you want to use it this way without the CLI/plugman, just unwrap the plugin JavaScript to not use cordova.define, and include them directly to your html page. 

The config.xml items are correct.

**Comment by krisrak** [comment]
what i meant was cordova_plugins.js is like below and accelerometer.js is in /plugin dir

```
cordova.define('cordova/plugin_list', function(require, exports, module) {
module.exports = [
    {
        "file": "plugins/org.apache.cordova.device-motion/www/Acceleration.js",
        "id": "org.apache.cordova.device-motion.Acceleration",
        "clobbers": [
            "Acceleration"
        ]
    },
    {
        "file": "plugins/org.apache.cordova.device-motion/www/accelerometer.js",
        "id": "org.apache.cordova.device-motion.accelerometer",
        "clobbers": [
            "navigator.accelerometer"
        ]
    },
    {
        "file": "plugins/org.apache.cordova.device-orientation/www/CompassError.js",
        "id": "org.apache.cordova.device-orientation.CompassError",
        "clobbers": [
            "CompassError"
        ]
    },
    {
        "file": "plugins/org.apache.cordova.device-orientation/www/CompassHeading.js",
        "id": "org.apache.cordova.device-orientation.CompassHeading",
        "clobbers": [
            "CompassHeading"
        ]
    },
    {
        "file": "plugins/org.apache.cordova.device-orientation/www/compass.js",
        "id": "org.apache.cordova.device-orientation.compass",
        "clobbers": [
            "navigator.compass"
        ]
    },
    {
        "file": "plugins/org.apache.cordova.camera/www/CameraConstants.js",
        "id": "org.apache.cordova.camera.Camera",
        "clobbers": [
            "Camera"
        ]
    },
    {
        "file": "plugins/org.apache.cordova.camera/www/CameraPopoverOptions.js",
        "id": "org.apache.cordova.camera.CameraPopoverOptions",
        "clobbers": [
            "CameraPopoverOptions"
        ]
    },
    {
        "file": "plugins/org.apache.cordova.camera/www/Camera.js",
        "id": "org.apache.cordova.camera.camera",
        "clobbers": [
            "navigator.camera"
        ]
    },
    {
        "file": "plugins/org.apache.cordova.camera/www/CameraPopoverHandle.js",
        "id": "org.apache.cordova.camera.CameraPopoverHandle",
        "clobbers": [
            "CameraPopoverHandle"
        ]
    },
    {
        "file": "plugins/org.apache.cordova.device/www/device.js",
        "id": "org.apache.cordova.device.device",
        "clobbers": [
            "device"
        ]
    }
];
module.exports.metadata = 
// TOP OF METADATA
{
    "org.apache.cordova.device-motion": "0.2.4",
    "org.apache.cordova.device-orientation": "0.3.6",
    "org.apache.cordova.camera": "0.2.9",
    "org.apache.cordova.device": "0.2.5"
}
// BOTTOM OF METADATA
});
```

i get did not hit deviceready in 5 seconds....

how to i fix it ?

**Comment by shazron** [comment]
I just told you, you don't need to use cordova_plugins.js, this is the domain of plugman/CLI. Please read what I said.

**Comment by krisrak** [comment]
I did use plugman to install plugins.
- It created Plugins folder with .m and .h files for plugins, and added to xcode project
- It created www folder with cordova_plugins.js and plugins/ folder with js files.
- www is not added to project, is this ok?

FYI, I'm not trying to load static html files within the www folder, I'm trying to load from a URL into the CordovaLib webview, like I told u when I opened this issue.
So my index.html and cordova.js is on the server (removed cordova_plugins.js from server) and I'm setting webView.startpage = my server URL/index.html, when the cordova webview launches, deviceready does not fire and plugin does not work with error undefined. (for the server URL of index.html check the email I sent)

what I'm I missing?

**Comment by krisrak** [comment]
The issue was `-force_load` linker option not added.
Without this the app complies but plugins did not work. When I setup the project first, adding `-force_load` was causing errors, so removed it. Later when I added, I did not get any error, and plugins also started working.
