### ISSUE TITLE
Cordova MediaPlugin change playback rate feature

### ISSUE THREAD

**Issue by wclr** [shazron/phonegap-questions#42]
There is an issue create in official repo with request to add playback rate change functionality.
https://issues.apache.org/jira/browse/CB-8098

Is it possible to speed up its implementatation?  We need it for our project and need someone who is in the loop and could help with this.

If no one can help than we could do it ourselfs. Its fearly easy to imlement in analogy with volume level change.
What what is needed for correct pull request that could be accepted?

**Comment by shazron** [comment]
hi @whitecolor your PR will be pulled in soon.  Discussion already here: https://github.com/apache/cordova-plugin-media/pull/40

**Comment by wclr** [comment]
@shazron  ok, i've added some auto tests for setRate hope it will run fine
