### ISSUE TITLE
about the cordova.js and it's plugin combination

### ISSUE THREAD

**Issue by laoyao** [shazron/phonegap-questions#43]
I am using the Cordova for my project. Is there any way can bundle all plugin js androd cordova.js into a whole one?
After searching a few days in google, the browserify is the must way.
Is there anybody had already face this question?

I am a newbee to nodejs. Browserify's doc is hard to understand.

**Comment by shazron** [comment]
Hi, 
cordova has this built in already, but under an experimental flag (soon to be mainlined) called "--browserify". See https://issues.apache.org/jira/browse/CB-7190

```
cordova --browserify prepare
cordova --browserify run
cordova --browserify plugin add org.apache.cordova.device
```

**Comment by laoyao** [comment]
I have already know this.
My project now have some customization about some plugin.
But browserify flag just bundle it when add plugin to project.

Is there any way to bundle cordova's all js into a bundle when plugins already added to the project?

**Comment by laoyao** [comment]
found this:
https://issues.apache.org/jira/browse/CB-7228

After runing‘cordova prepare —browserify' in my iOS project dir.
The cordova_plugin.js and all plugins’ js had gone, but I found that the final cordova.js not contain any plugins js content.

Is there any other flag to assign this cmd?

**Comment by shazron** [comment]
If you have customization in a plugin, have a separate folder location or repo with the original plugin source plus your code changes, and "cordova plugin add" it using the browserify flag.

If your final cordova.js does not contain the plugin js, it's a bug (but I doubt that it didn't work) so please file an issue in the Apache Cordova jira.

**Comment by barsh** [comment]
Has anyone been able to get this to work?

```
cordova create May12
cd May12
cordova platform add ios
cordova --browserify plugin add cordova-plugin-device
cordova --browserify run
```

I get a ton of these errors when I connect the Safari Developer Console to the iOS simulator.

```
Cannot find module '/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/cordova-js/src/ios/exec'
```

**Comment by shazron** [comment]
Hi @barsh - could you file an issue at http://issues.cordova.io ? A cordova dev is currently working on issues with browserify
