### ISSUE TITLE
Method to avoid HTTP Basic auth credential caching

### ISSUE THREAD

**Issue by nachomp** [shazron/phonegap-questions#44]
Dear all:

Our most recent project has forced us into HTTP Basic authentication for an iOS app. After first authentication, subsequent remote calls for authentication, performed with JQuery, include the Authentication header with the token obtained after the first call for authentication. This is, we are doomed to be connected to the service with the same user regardless of the user/pass that we try to use. Only app uninstall/install process lets us log in as a different user, and then the new Authentication token is used forevermore until a subsequent uninstall/install process.

We are using Cordova iOS 3.6.3 because of the bug in 3.7.0 which creates an additional "gap://ready" iframe after each call to the file plugin but the same seems to be happening with Cordova iOS 3.7.0.

It seems to be a well known issue in iOS development, as seen in http://stackoverflow.com/questions/11099442/basic-authentication-logout-on-iphone , http://stackoverflow.com/questions/7256808/clear-the-credentials-from-uiwebview/18143902#18143902 or https://gist.github.com/jfahrenkrug/27421

We have tried all the options commented in those previous posts at some different points of Cordova 3.6.3 iOS platform's code, but with no success.

For instance, we thought that using the canonicalRequestForRequest method at CDVURLProtocol.m would be a perfect point to be able to remove the Authentication HTTP Request header or try with the hash technique commented in the gist referenced above, but this method is actually never called.

We also tried, as some of the other posts aforementioned recommended, deleting all the credentials at the sharedCredentialStorage at different points of the application. However, the dictionary [[NSURLCredentialStorage sharedCredentialStorage] allCredentials]
is always empty, although at least one username/pass pair has been successfully used before reaching the code introduced.

Has anyone solved this situation before or provide me with a hint so I can try an additional method to avoid HTTP Basic auth credential caching? I'll be glad to post the solution here as I find it.

Thanks everyone for your help in advance. Cheers!

**Comment by shazron** [comment]
For the 3.7.0 bug, you can hotfix it if you want: https://issues.apache.org/jira/browse/CB-8002?focusedCommentId=14280609&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14280609

You can grab the request from the canInitWithRequest method (self.request). The request here could possibly be a NSMutableURLRequest, you'll have to check at runtime, and cast it (so you could clear a header field, for example).

**Comment by nacho-marin** [comment]
Great! We'll test the 3.7.0 hotfix until 3.8.0 is out.

One of the first things I tried was working with the request inside canInitWithRequest, but self.request is an NSURLRequest (non mutable) :( 

It is weird that canonicalRequestForRequest is never called. I'll keep studying this issue as soon as I have time.

For now, we could solve it by forgetting modifications in the iOS platform and sticking to the HTTP Authentication: Basic and Digest Access Authentication (https://www.ietf.org/rfc/rfc2617.txt). The answer was there and we were blind to see it. All you need is that the remote server provides a logout URL that returns a 401. Then the local HTTP management stack removes cached Basic auth credential. Fortunately, we were Cordovizing an existing webapp and they have a log out URL. As we call it, we can log in again with a different user/pass. The ugly thing is that the  401 response contains their whole HTML document representing the "you are logged out" document.

As logout button in our app may be tapped when the device is offline, what we do is to log out before logging in when the user submits login and password in the login form.

If the remote service did not take care of providing a "logout" page o, better, a logout REST method, I guess that it should be possible to play with the iOS URL loading system to force a 401 when you access a fake "https://example.com/logout" URL. But, considering that we cannot manipulate (or at least I haven't found the way) the request in the Cordova iOS platform, I will try to find out if it can be done.

Thanks, Shazron!
