### ISSUE TITLE
The use of phonegap WebView JS injection in the Android 4.3 system version, return the results of delays, that is to use JS loadurl method to load caused by thread occlusion, how to solve?

### ISSUE THREAD

**Issue by gaobin881201** [shazron/phonegap-questions#45]
This is my code
if (android.os.Build.VERSION.SDK_INT < 19) {
            cordovaWebView.loadUrl("javascript:" + js.toString());
                    } else {
                        cordovaWebView.evaluateJavascript(
                                "javascript:" + js.toString(), null);
                    }

**Comment by shazron** [comment]
Sorry, this is a specific Android version question, of which I'm not the expert in. It's best if you file an issue at: http://issues.apache.org/jira/browse/CB
