### ISSUE TITLE
SplashScreen PhoneGap plugin should not reorient splash screen on iPhone 5/5S

### ISSUE THREAD

**Issue by networksolution** [shazron/phonegap-questions#46]
Hi.

I’m using the Splash Screen Phonegap plugin. On iPhone 5/5S the Splash Screen should not reorient. The native behavior of splash screens in any native iPhone 5 app is to not reorient.

Splash screen reorientation is available only on iPhone 6/6 Plus and all iPads and Androids... but not on iPhone 5/5S/4S/4/3GS/3.

Thank you in advance.

Dr. Marco Marsala
Network Solution srl

**Comment by shazron** [comment]
Hi, this is not a question but a bug report (as mentioned in the README.md). I've already given you the information on where to file it:

Please file an issue at:
http://issues.apache.org/jira/browse/CB

... so it can be tracked and evaluated by the devs, and you can be notified.

Sign up here:
https://issues.apache.org/jira/secure/Signup!default.jspa

Thanks!
