### ISSUE TITLE
 Using Cordova and his plugins on a remote url

### ISSUE THREAD

**Issue by tahola** [shazron/phonegap-questions#47]
I know this question have been asked but i stil dont get it, I like to use Cordova and his plugins (InAppBrowser and SocialSharing) with a remote webapp. 

Now on oppening, my application load an external webapp like this `<content src="http://mywebapp.domain.com" />`, everything is fine except that with this method i dont have access to any plugins.

So i also tried with jquery :
**config.xml**
`<content src="index.html" />
<access origin="*" />`

**index.html :**
`$(document).ready( function() 
 { 
 $('body').load('http://mywebapp.domain.com');
});`

With this i have access to cordova and all the plugins but the rooting inside of http://mywebapp.domain.com dont work anymore (no css, no js, no route..) and the method look very "dirty".

So my question is, what is the proper way to do it ? (Thank)

**Comment by shazron** [comment]
The external web app should load cordova.js in its domain, including any plugin js.

**Comment by tahola** [comment]
Yes thank, Its finally work :+1: 

For informations I had to include this on my remote page :
`<script src="/js/cordova.js"></script>`
`<script src="/js/inappbrowser.js"></script>`
and apparently `cordova_plugins.js` must be in the /js/ folder to (same folder as cordova.js).
