### ISSUE TITLE
Cordova WKWebView Engine => Issues with CORS

### ISSUE THREAD

**Issue by iOSTeamIntuiLab** [shazron/phonegap-questions#48]
Hi,

We are currently trying to use the WKWebView inside Cordova.
We followed the instructions indicated in https://github.com/apache/cordova-plugins/tree/master/wkwebview-engine.
However, we have an issue to get some resources from remote servers. We get the classic CORS issue but as we do not own the various remote servers (S3 buckets of customers, dropbox, etc.) we cannot change the cross origin policy of these ones.

We have an access origin \* in our config.xml but it does not seem to be taken into account.
By searching on the Cordova Jira tool, we've found this opened issue: https://issues.apache.org/jira/browse/CB-7049

Could you tell us if the whitelist should be taken into account now or not (did you manage to intercept requests of the wkwebview to manage this whitelist or not) ?
- If so, what do we do wrong ?
- If not, do you have a workaround we could use ?

Thank you.

Anthony.

**Comment by shazron** [comment]
Hi,
This is a solution that I haven't fixed or found a workaround for yet. I encourage you to continue the discussion in that JIRA issue, since this issue hasn't been worked on yet.
