### ISSUE TITLE
Flag for .xcworkspace

### ISSUE THREAD

**Issue by RobbyChapman** [shazron/phonegap-questions#49]
I had a particular use case where I was leveraging CocoaPods in my project. By default, pods will put the project in an .xcworkspace. By doing so, it breaks cordova's build scripts(3.7.0). Inside the build script it is explicitly passing -target and -project params. It is an easy fix on my end to swap the build params to a -workspace -scheme paradigm. But I was just curious, do you think other developers would benefit such flexibility? If so, is it something you would be interested in? I can create a pull request with a version of the build script if it is desirable. 

Here is an example of a modified version of build.sh. I hard coded .xcworkspace, but ideally it would be a optional parameters to either build a project, or a workspace. I know you have converted them to node in 3.8, but just as an example:

CORDOVA_PATH=$( cd "$( dirname "$0" )" && pwd -P)
PROJECT_PATH="$(dirname "$CORDOVA_PATH")"
XCODEPROJ=$( ls "$PROJECT_PATH" | grep .xcworkspace  )
PROJECT_NAME=$(basename "$XCODEPROJ" .xcworkspace)

source "$CORDOVA_PATH/check_reqs"

cd "$PROJECT_PATH"

APP=build/$PROJECT_NAME.app

CONFIGURATION=Debug
EMULATOR=1
DEVICE=0
while [[ $# -gt 0 ]]; do
    case "$1" in
        --debug) ;;
        --release) CONFIGURATION=Release;;
        --device) EMULATOR=0;;
        --emulator) ;;
        *) echo "Unrecognized flag: $1"; exit 2;;
    esac
    shift
done

if (( $EMULATOR )); then
    exec xcodebuild -workspace "$PROJECT_NAME.xcworkspace" -arch i386 -scheme "$PROJECT_NAME" -configuration $CONFIGURATION -sdk iphonesimulator build VALID_ARCHS="i386" CONFIGURATION_BUILD_DIR="$PROJECT_PATH/build/emulator" SHARED_PRECOMPS_DIR="$PROJECT_PATH/build/sharedpch"
else
    exec xcodebuild -xcconfig "$CORDOVA_PATH/build$(echo -$CONFIGURATION | tr '[:upper:]' '[:lower:]').xcconfig" -workspace "$PROJECT_NAME.xcworkspace" ARCHS="armv7 armv7s arm64" -scheme "$PROJECT_NAME" -configuration $CONFIGURATION -sdk iphoneos build VALID_ARCHS="armv7 armv7s arm64" CONFIGURATION_BUILD_DIR="$PROJECT_PATH/build/device" SHARED_PRECOMPS_DIR="$PROJECT_PATH/build/sharedpch"
fi

**Comment by shazron** [comment]
Thanks @RobbyChapman -- we're already going with workspace support in cordova-ios 4.x, here's the relevant issue: https://issues.apache.org/jira/browse/CB-5921 (eta: sometime in the next two months).
