### ISSUE TITLE
 Best recommended practice to debug phonegap applications on iOS devices?

### ISSUE THREAD

**Issue by shazron** [shazron/phonegap-questions#5]
In my opinion, in order of best preferred to least:
1. Use desktop Safari 6.x (for both a device and the iOS Simulator): http://moduscreate.com/enable-remote-web-inspector-in-ios-6/ 
2. Use Adobe Edge Inspect (formerly known as Shadow), available on the free tier of Adobe Creative Cloud: http://html.adobe.com/edge/inspect/
3. Use Weinre (you must self host), which Adobe Edge Inspect is based on: https://github.com/apache/cordova-weinre
4. Use http://debug.phonegap.com, a hosted version of Weinre, part of Adobe PhoneGap Build's service. Don't forget to choose a guid only you know, if not other people can inspect your device!
5. https://github.com/google/ios-webkit-debug-proxy/ (this is only last since I haven't used it to form an opinion. This allows you to use the Chrome Web Inspector)

**Comment by mgcrea** [comment]
I'd love to use desktop Safari, however the `console` is hijacked by xcode.

See https://issues.apache.org/jira/browse/CB-3959

Any ideas?

**Comment by shazron** [comment]
@mcgrea, It is fixed in 2.8.0: https://issues.apache.org/jira/browse/CB-3327
