### ISSUE TITLE
cordova android gradle question

### ISSUE THREAD

**Issue by laoyao** [shazron/phonegap-questions#50]
I am using cordova4.0 to develop my app.

I want to add some extra lib to my project. 
gradle file is following:

dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
    compile 'com.afollestad:material-dialogs:0.6.7.1'// my added file
    // SUB-PROJECT DEPENDENCIES START
    debugCompile project(path: ":CordovaLib", configuration: "debug")
    releaseCompile project(path: ":CordovaLib", configuration: "release")
    // SUB-PROJECT DEPENDENCIES
}

Is there anybody give me some advise?
![2015-05-25 18 35 21](https://cloud.githubusercontent.com/assets/870777/7796028/8b45eeda-030d-11e5-998e-6d90ef3e49cd.png)

**Comment by shazron** [comment]
Sadly, not a cordova-android expert. Try StackOverflow or file an issue at http://issues.cordova.io
