### ISSUE TITLE
Image Crop not working in Android 5 Version and above

### ISSUE THREAD

**Issue by manikandan-b** [shazron/phonegap-questions#51]
@shazron  
Hi shazron i am doing personal project in that i am using profile picture take from camera using phonegap camera plugin and alowEdit property. Image crop working fine in lower version of android but in 5 and above its not working while taking photo but its working fine taking photo from gallery in above 5 version. Can you please give suggestion regarding this issue ASAP?

**Comment by shazron** [comment]
In this case I can't offer any help since I'm focused on iOS mainly. You can try filing an issue with a reproducible test case reduction at issues.cordova.io
