### ISSUE TITLE
iOS9 multitasking and UIWebView

### ISSUE THREAD

**Issue by nickredding** [shazron/phonegap-questions#52]
UIWevView is not dealing with window resize properly when using iOS9 multitasking on iPad Air 2. If the cordova app is pulled out from the right, the screen resize events show bogus widths--much larger than actual, resulting in incorrect page rendering. if the app is squeezed to the left by another app being pulled out, the resizing works properly. This problem does not occur with Safari, so the issue must be somewhere between iOS webview and cordova. Any insight into how to resolve this?

**Comment by nickredding** [comment]
Update - this is caused by the statusbar plugin. I checked with the trivial cordova Hello project and the same issue arises when the statusbas plugin is added.

**Comment by nickredding** [comment]
Update - I found the cause -- the line

[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(statusBarDidChangeFrame:) name: UIApplicationDidChangeStatusBarFrameNotification object:nil];

in pluginInitialize. If commented out, the problem no longer arises. I'm not sure yet what the negative impact of removing this could be.

**Comment by shazron** [comment]
Thanks @nickredding - seems to me this is more of a bug report, I assume you have an issue filed at issues.cordova.io?

**Comment by nickredding** [comment]
Yes,  CB-10288 https://issues.apache.org/jira/browse/CB-10288

**Comment by shazron** [comment]
Thanks!
