### ISSUE TITLE
WKWebView load external file url

### ISSUE THREAD

**Issue by kanoshin** [shazron/phonegap-questions#53]
Hi, @shazron!

In my app I'm saving new index.html to the Documents folder. Then trying to navigate there using `location=...` code. It doesn't work and I found issue about it on cordova tracker. The question is why is it possible to load index.html from application directory and not possible to load another file?

I can see that in your plugin you are using the following code to load index:

```
if ([self canLoadRequest:request]) { // can load, differentiate between file urls and other schemes
        if (request.URL.fileURL) {
            SEL wk_sel = NSSelectorFromString(CDV_WKWEBVIEW_FILE_URL_LOAD_SELECTOR);
            NSURL* readAccessUrl = [request.URL URLByDeletingLastPathComponent];
            return ((id (*)(id, SEL, id, id))objc_msgSend)(_engineWebView, wk_sel, request.URL, readAccessUrl);
        } else {
            return [(WKWebView*)_engineWebView loadRequest:request];
        }
    }
```

I tried to change the request here to point on Documents folder, but it still doesn't work (opens about:blank). Is it possible to write plugin that will load such url?

**Comment by kanoshin** [comment]
I was able to load file from Document folder with help of `location=...` after removed if-else from the code above. Now I have:

```
if ([self canLoadRequest:request]) { // can load, differentiate between file urls and other schemes
        return [(WKWebView*)_engineWebView loadRequest:request];
    }
```

Could you please explain the purpose of it?

**Comment by shazron** [comment]
As a reference to others - here's the code we are talking about: https://github.com/apache/cordova-plugin-wkwebview-engine/blob/1bc5766b4aa968a7707d2361c7224074ec41349a/src/ios/CDVWKWebViewEngine.m#L96-L102

If I have this right, you already load the default index.html, and load your new index.html from `Documents` by using JavaScript (window.location) in index.html, correct?

The reason that `if` statement is there is to differentiate between file protocol requests and other requests -- file protocol requests need to use a specialized method on WKWebView and not the general loadRequest method.

What iOS version did you test on, and was it the Simulator or device?

**Comment by kanoshin** [comment]
Oh, I was working on simulator. It doesn't work on real device with IOS 9.2. But I was finally able to load external index.html sending modified url to the loadRequest mehod of CDVWKWebViewEngine implementation. Now it requires app restart to do so. 

I'm going to try calling something like loadRequest from js code. Bad thing is that I don't really understand what am i doing.

**Comment by shazron** [comment]
Ah yes, the Simulator has no security restrictions so it will allow file protocol requests from anywhere. I would only test on the device to get true results. See: https://github.com/shazron/WKWebViewFIleUrlTest

**Comment by kanoshin** [comment]
Finally I ended up with solution that copy www folder to the documents folder (with help of my plugin), then starts from it and loads some stuff from server to redirect there. Bad thing is that I had to override loadRequest method in wkwebview plugin to load my url.

Is it possible to set `<content src="..">` in config.xml to point on my index.html from documents folder? It seems that it can open files only from app bundle.

**Comment by shazron** [comment]
Sorry for the late reply. Unfortunately `<content src=".." />` is relative to the www folder in the app package, or a http protocol url.

My advice to you is, create a new plugin, and add a `<dependency>` to the wkwebview-engine plugin. In your plugin, then subclass `CDVWKWebViewEngine` and add your override there instead (and call the superclass implementation if you don't handle the call). Make sure you have this in your plugin.xml, with the your subclass' name: https://github.com/apache/cordova-plugin-wkwebview-engine/blob/73118f95e7e1a3bd8fc9ce3475cffea7153593d9/plugin.xml#L44-L49
