### ISSUE TITLE
WkWebView InAppBrowser

### ISSUE THREAD

**Issue by ramezrafla** [shazron/phonegap-questions#54]
Hi @shazron 
Thanks a lot for taking questions from your community. Your blog is also amazing. Love working with folks from Adobe!

My question relates to the InAppBrowser and using WkWebView. Is there a process now? We can use WkWebView for the main WebView but it seems we are still stuck with UIWebView for the InAppBrowser.

I noticed your WkWebView branch here: https://github.com/apache/cordova-plugin-inappbrowser/tree/wkwebview

But it hasn't been updated in 2 years. Your advice would be greatly appreciated.

Thanks a lot!

**Comment by shazron** [comment]
Hi,
I'm afraid that converting the IAB to use WKWebView has stalled (there were complications in converting in the first place), and there are other pressing needs to be worked on right now. So, to answer your question -- unless someone else picks up this work, it won't get done unfortunately :/
