### ISSUE TITLE
How to check if app is running on the device and know when it has exited?

### ISSUE THREAD

**Issue by pMaske** [shazron/phonegap-questions#56]
Hi @shazron ,  I am trying to automate ios unit test runs on a physical device. I am trying to write a shell script to achieve this. My workflow so far is
- Build the app (using msbuild)
- deploy the app using ios-deploy. ( I want to pass arguments to the app, which is not working though with v1.9.2)
- In the automation script I would like to keep checking if the process i.e my app , is running in a while loop. As soon as my test runs are completes/or crashes,the app will exit. At this point process id will become empty and I want to exit the lldb.
Can you please shed some light of how I can check if the process is running and know when it has exited (either due to a crash or successful test completion).

**Comment by shazron** [comment]
Sorry I don't have answers to these questions. Perhaps more people can help on the ios-deploy repo?
