### ISSUE TITLE
WKWebView issue with loading local file URLs

### ISSUE THREAD

**Issue by vsvikram** [shazron/phonegap-questions#58]
I have the following error on the console when I'm using the app on the actual device (iPad running iOS 11.4) but not on simulator. In my case, I'm trying to load local images with the src as file:///var/mobile/containers/.../Documents/..../abc.jpg. I'm using WKWebView in my Cordova hybrid app with Salesforce SDK 6.1, Cordova 8.0, Cordova-iOS 4.5.4.
**Error: failed to load resource.. operation not permitted.. kCFErrorDomainCFNetwork**

In the simulator, it all works fine. But not on the actual device. What is the suggested workaround for loading resources which are not under www directory in WKWebView apps that doesn't require me to use a local server and then serve the app?

I think Apple has provided a fix for this and it requires us to use -loadFileURL:allowingReadAccessToURL: in the WKWebView implementation. But I'm not sure how this can be implemented in my case with the existing implementation of Salesforce SDK and Cordova.

Any insights in the matter will be highly appreciated.

**Comment by shazron** [comment]
We already use that API. You can only load it from a relative path from the www not any sibling folders of it.
