### ISSUE TITLE
Phonegap app crashes on resume (iOS) when using Web Audio API

### ISSUE THREAD

**Issue by Oberto** [shazron/phonegap-questions#7]
I added audio using Web Audio API (which as of ios 6 is supported). It works well; except when I exit the app then re-open the app (from being "Backgrounded"), the app now pauses then crashes.

Is this a Phonegap issue?

**Comment by shazron** [comment]
I won't know for sure without some sample code (so we can be on the same page for a bug repro). It's best if you file an issue at http://issues.cordova.io so this thing can be put in the queue so any dev can pick this up for investigation and possible resolution.

**Comment by shazron** [comment]
Please file an issue at:
http://issues.cordova.io

... so it can be tracked and evaluated by the devs, and you can be notified.

Sign up here:
https://issues.apache.org/jira/secure/Signup!default.jspa

Thanks!
