### ISSUE TITLE
When my device is offline, the method getCurrentPosition takes forever to return a position... A solution?

### ISSUE THREAD

**Issue by shazron** [shazron/phonegap-questions#8]
From https://twitter.com/leiluspocus/status/316659556166029312

**Comment by shazron** [comment]
That's probably waiting for a timeout (you can set how long for getCurrentPosition _[1]_). Also try using the Connection API _[2]_ (it's fast) before calling.

[1] http://docs.phonegap.com/en/2.5.0/cordova_geolocation_geolocation.md.html#geolocationOptions
[2] http://docs.phonegap.com/en/2.5.0/cordova_connection_connection.md.html#connection.type

**Comment by leiluspocus** [comment]
Not sure to see how the connection type can be useful. Is that something like this that you meant by "try using the Connection API" ?
http://jsfiddle.net/leiluspocus/s3FSD/1/

**Comment by shazron** [comment]
What I meant was to check the connection first, if it was NONE or UNKNOWN, you know that there is a good chance that geolocation might fail (although with devices with GPS chips, it might just take longer, but not fail if there is no cellular connection). 

The connection API could give you a hint on how the geolocation call will do -- and you can warn the user accordingly I suppose and/or use a longer timeout.

**Comment by ppcano** [comment]
@shazron, Using Cordova 2.5 and I have navigator.connection.type === wifi, the timeout option and getCurrentPosition does not work correctly.

**Comment by shazron** [comment]
@ppcano your situation might be different. Kick up a new issue and we can discuss there.

**Comment by leiluspocus** [comment]
Ok, I got it. Thanks shazron for your answers !
